export const allZmanim = [
  { key: 'alotHaShachar', labelKey: 'ALOT_HASHACHAR' },
  { key: 'misheyakir', labelKey: 'MISHEYAKIR' },
  { key: 'misheyakirMachmir', labelKey: 'MISHEYAKIR_MACHMIR' },
  { key: 'dawn', labelKey: 'DAWN' },
  { key: 'sunrise', labelKey: 'NETZ_HAJAMA' },
  { key: 'sofZmanShma', labelKey: 'SOF_SHEMA' },
  { key: 'sofZmanTfilla', labelKey: 'SOF_TFILA' },
  { key: 'chatzot', labelKey: 'CHATZOT' },
  { key: 'minchaGedola', labelKey: 'MINCHA_GEDOLA' },
  { key: 'minchaKetana', labelKey: 'MINCHA_KETANA' },
  { key: 'plagHaMincha', labelKey: 'PLAG_HAMINCHA' },
  { key: 'shkiah', labelKey: 'SHKIA' },
  { key: 'beinHaShmashos', labelKey: 'BEIN_HASHMASHOS' },
  { key: 'tzeit', labelKey: 'TZEIT' },
  { key: 'tzeit42min', labelKey: 'TZEIT_42' },
  { key: 'tzeit72min', labelKey: 'TZEIT_72' },
  { key: 'chatzotNight', labelKey: 'CHATZOT_NIGHT' },
];