export const allStudies = [
  { key: 'JUMASH', labelKey: 'JUMASH_TITLE' },
  { key: 'TEHILIM', labelKey: 'TEHILIM_TITLE' },
  { key: 'TANYA', labelKey: 'TANYA_TITLE' },
  { key: 'SEFER_HAMITZVOT', labelKey: 'SEFER_HAMITZVOT_TITLE' },
  { key: 'RAMBAM_1', labelKey: 'RAMBAM_1_TITLE' },
  { key: 'RAMBAM_3', labelKey: 'RAMBAM_3_TITLE' },
  { key: 'PARASHA', labelKey: 'PARASHA_TITLE' },
  { key: 'HAFTARA', labelKey: 'HAFTARA_TITLE' },
  { key: 'DAF_YOMI', labelKey: 'DAF_YOMI_TITLE' },
  { key: 'YERUSHALMI_YOMI', labelKey: 'YERUSHALMI_YOMI_TITLE' },
  { key: 'MISHNA_YOMI', labelKey: 'MISHNA_YOMI_TITLE' },
  { key: 'NACH_YOMI', labelKey: 'NACH_YOMI_TITLE' },
  { key: 'TEHILLIM_YOMI', labelKey: 'TEHILLIM_YOMI_TITLE' },
  { key: 'HAYOM_YOM', labelKey: 'HAYOM_YOM_TITLE' },
];